on:
  workflow_dispatch:

jobs:
  version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.version.outputs.current-version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: corepack enable && yarn

      - name: Build extension
        run: yarn package

      - name: Publish extension
        run: yarn deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload to releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{needs.version.outputs.version}}
          make_latest: true
          files: |
            vsc-discord-rpc-${{needs.version.outputs.version}}.vsix
